#!/bin/bash

{
   echo "showpid"
   echo "showpid usless arguments"
   echo "showpid uselees arguments 80 chars ?? 123!@# hfvdjxsjdh cvbxnzmujds 23456632jhh"
   echo "pwd"
   echo "pwd useless arguments"
   echo "pwd 20 arguments test 2 3 sha-ger rty cvb jk tyu dfg cb yu fgh cvb ty fh ck 1 2"
   echo "cd -"
   echo "cd two args"
   echo "cd too many argumats"
   echo "cd no/path"
   echo "cd /home/os/workspace"
   echo "pwd"
   echo "cd .."
   echo "pwd"
   echo "cd -"
   echo "pwd"
   echo "cd -"
   echo "pwd"
   echo "jobs"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 8 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 13 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 8 &"
   echo "/bin/sleep 1 &"
   echo "/bin/sleep 3 &"
   echo "jobs"
   echo "kill -9 10"
   echo "kill 8 1"
   echo "kill -9 1 3"
   echo "/bin/sleep 4"
   echo "jobs"
   echo "/bin/sleep 1 &"
   echo "jobs"
   echo "/bin/sleep 4"
   echo "jobs"
   echo "/bin/sleep 5"
   echo "jobs"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 1 &"
   echo "/bin/sleep 8 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 1 &"
   echo "/bin/sleep 8 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 1 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 100 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 1 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 8 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 1 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 100 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 1 &"
   echo "/bin/sleep 2   &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 2   &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 1 &"
   echo "/bin/sleep   3 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 1 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep             1 &"
   echo "/bin/sleep 8 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 1   &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 1 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 1 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 1 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 8 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 100     &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 1 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 1 &"
   echo "/bin/sleep 3      &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep     8 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 1 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 2 &"
   echo "/bin/sleep 1 &"
   echo "/bin/sleep 3 &"
   echo "/bin/sleep     8 &"
   echo "jobs"
   echo "false_external_job"
   echo "false_external_background_job &"
   echo "jobs"
   sleep 3
   echo "quit"
} | ./smash
